### ISSUE TITLE
Passing urls as a variable with the Circle CI orb

### ISSUE THREAD

**Issue by griable** [foo-software/lighthouse-check#45] opened 2021-04-06 16:11 UTC
Hi there,

First, I'm truly sorry if this is not the right place for posting issues about CircleCI Orb but I couldn't find an other place.

I'm currently working on a simple Circle CI flow which responsibility is :
- building the site (`npm build`)
- publishing it to Netlify Preview and getting the url (using Netlify-cli)
- getting the lighthouse score against the aforementioned url (using lighthouse orb)

My problem is that I can't get my dynamic URL to be passed as a parameter as it's not defined upfront.

Here's my code :

```executors:
  node:
    docker:
      - image: circleci/node:erbium

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      keys:
        - v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}

  install_node_modules: &install_node_modules
    run:
      name: Install NPM dependencies
      command: npm install

  save_cache: &save_cache
    save_cache:
      name: Save NPM package cache
      key: v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
      paths:
        - ./node_modules

version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.13

jobs:
  install:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
  build_and_lint:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: Build Public
          command: npm run generate
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: install netlify cli
          command: sudo npm install -g --unsafe-perm --silent netlify-cli
      - run:
          name: deploy site to netlify
          command: |
            netlify deploy | awk '/Website Draft URL: /{print $0}' | sed  's/.* \(.*\)/\1/' > ./echo-output
      - persist_to_workspace:
          root: ./
          paths:
            - echo-output
  run_ligthouse:
    executor: lighthouse-check/default
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Print value
          command: cat ./echo-output                
      - lighthouse-check/audit:
          urls: $(<./echo-output)

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install
      - build_and_lint:
          requires:
            - install
      - deploy:
          context: NuxtNetlify
          requires:
            - build_and_lint
      - run_ligthouse:
          requires:
              - deploy
```

I'll happily provide more details if unclear. Thanks for taking time to those who read this!

**Comment by adamhenson** [comment] 2021-04-07 02:03
@griable - I'm sorry you're having this problem, but if I understand correctly - this is not caused by this project nor is it an expectation this project is intended to fulfill. I'd love to help you debug it, but since it's unrelated I can't make the time unfortunately.

I'd suggest limiting your example to take everything out of the equation besides what you're trying to accomplish to start. If I understand correctly you are trying to persist the Netlify URL string between jobs. I've never used Netlify, so my advice is limited. Did you confirm the part where you write the file is working? I see you're doing this:
```
command: |
            netlify deploy | awk '/Website Draft URL: /{print $0}' | sed  's/.* \(.*\)/\1/' > ./echo-output
```
For starters you should add a line after that to at least confirm this is being written to a file (`cat ./echo-output`). Additionally it looks like your file doesn't have an extension. I'm not sure if that would cause an issue, but I'd add a `.txt` extension.

That's the best advice I can give, but unrelated to this project, so I'll need to close this. Also, in the future if you do come across an issue with the CircleCI Orb, please open an issue in the [`lighthouse-check-orb`](https://github.com/foo-software/lighthouse-check-orb) repo. Good luck!

**Closed as completed by adamhenson** 2021-04-07 02:03 UTC
