### ISSUE TITLE
Lighthouse performance result 0

### ISSUE THREAD

**Issue by robert-kmieciak-vmltech** [foo-software/lighthouse-check#52] opened 2021-07-20 13:42 UTC
Hi there, 
I am getting `performance` result `0` while running Lighthouse Check - and have no idea why. Any ide what I am missing? 

My pipeline configuration: 
```
   - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          urls: '${{ steps.get_project_url.outputs.prop }}'
          prCommentEnabled: true
          prCommentSaveOld: false
          throttling: 'mobileSlow4G'
          emulatedFormFactor: 'mobile'`

      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "80"
          minBestPracticesScore: "80"
          minPerformanceScore: "0"
          minProgressiveWebAppScore: "60"
          minSeoScore: "80"
```

GH Actions logs display this 
![image](https://user-images.githubusercontent.com/81171488/126333522-dcd7256e-5ef8-4c16-be2f-7bcbbca8d323.png)

**Comment by adamhenson** [comment] 2021-07-20 15:22
Hello @robert-kmieciak-wttech. I would suggest that you simply look at the Lighthouse report. Since the other metrics are populated, my guess would be there is a legitimate problem with the website.

You can save Lighthouse reports as [artifacts](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts). This should reveal the problem. You can refer to the [standard example](https://github.com/foo-software/lighthouse-check-action#usage-standard-example) on how to do this, but it would just be a matter of adding `- run: mkdir /tmp/artifacts` and the `Upload artifacts` block.

**Comment by robert-kmieciak-vmltech** [comment] 2021-07-20 18:23
hi @adamhenson 
I will check generated report. Funny thing is that while running lighthouse manually it works. I will get back to you when I work with report. Thanks

**Comment by adamhenson** [comment] 2021-07-20 21:36
Closing this because there are many reasons why a Lighthouse performance score can be 0. The report will surface the exact reasons. It's apparent that in this case the source of the performance score being 0 doesn't relate to this project, since the audit completed successfully and other metrics came back with a score above 0.

@robert-kmieciak-wttech - if you do determine the cause, please feel free to post here for others. And if you do find an issue that relates to this project, please don't hesitate to open an issue with specific details.

**Closed as completed by adamhenson** 2021-07-20 21:36 UTC

**Comment by robert-kmieciak-vmltech** [comment] 2021-07-21 06:08
Thank you @adamhenson for assistance. 
As you advised I've checked lighthouse report and it is showing error as on screenshot 
![image](https://user-images.githubusercontent.com/81171488/126439498-cfdf2fbd-47e0-4c8d-98eb-130f16d779de.png)

So I am now checking which version of chrome we are using and will upgrade it. 
Anyway this is it for this issue. 

One more time thank you
